### ISSUE TITLE
(fetch_tweets) Network response was not ok, retrying in 10 seconds (chrome)

### ISSUE THREAD

**Issue by demerge** [teisseire117/DeleteTweets#1]
(fetch_tweets) Network response was not ok, retrying in 10 seconds
![Screenshot (61)](https://github.com/teisseire117/DeleteTweets/assets/79563447/c6f60ba6-caff-4ef3-bb23-f6ff1fb916bb)

**Comment by teisseire117** [comment]
Click on the promise and show me the full error message

**Comment by demerge** [comment]
yes, i did.
![Screenshot (62)](https://github.com/teisseire117/DeleteTweets/assets/79563447/88ecfab2-c157-4b03-8cb4-e02fc65bb5d4)

**Comment by teisseire117** [comment]
> yes, i did. ![Screenshot (62)](https://user-images.githubusercontent.com/79563447/263076095-88ecfab2-c157-4b03-8cb4-e02fc65bb5d4.png)

In the authorization variable, did you keep the 'Bearer' word with the key ?

**Comment by demerge** [comment]
![Screenshot (63)](https://github.com/teisseire117/DeleteTweets/assets/79563447/ea040290-f839-439f-92e7-b45a80296fda)

**Comment by demerge** [comment]
No, i did not keep the bearer word with the key

**Comment by teisseire117** [comment]
> No, i did not keep the bearer word with the key

You need to keep it, try again and see if it works

**Comment by demerge** [comment]
Promise {<pending>}[[Prototype]]: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: "Rate limit exceeded\n"

**Comment by teisseire117** [comment]
> Promise {}[[Prototype]]: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: "Rate limit exceeded\n"

Did it do it right after you launched the script, or in the middle of it ? Also how many tweets is there to delete ? I'll set up something to deal with rate limits better than that

**Comment by demerge** [comment]
over a thousand messages i guess

**Comment by demerge** [comment]
> > Promise {}[[Prototype]]: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: "Rate limit exceeded\n"
> 
> Did it do it right after you launched the script, or in the middle of it ? Also how many tweets is there to delete ? I'll set up something to deal with rate limits better than that

yes, it was fetching my posted tweet but stoped and gave that error.

**Comment by teisseire117** [comment]
> > > Promise {}[[Prototype]]: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: "Rate limit exceeded\n"
> > 
> > 
> > Did it do it right after you launched the script, or in the middle of it ? Also how many tweets is there to delete ? I'll set up something to deal with rate limits better than that
> 
> yes, it was fetching my posted tweet but stoped and gave that error.

Alright I updated the script, get the new one and try again.

Now it will fetch 1 batch of 20~ tweets, and remove it, then move on to next batch. In case of ratelimit it now sleeps for 1 minute.

Before it would wait to fetch all the tweets before trying to delete them, which in case of a crash in the middle mean nothing would have been deleted. It also didn't have proper sleep time for ratelimit.

**Comment by demerge** [comment]
![Screenshot (65)](https://github.com/teisseire117/DeleteTweets/assets/79563447/c020c730-1a06-4143-a6c2-a97898af815b)
the script was running earlier, and several tweets was deleted. My pc went on sleep mode, i found the process stopped, i restarted but i got this error.
thanks.

**Comment by teisseire117** [comment]
> ![Screenshot (65)](https://user-images.githubusercontent.com/79563447/263226606-c020c730-1a06-4143-a6c2-a97898af815b.png) the script was running earlier, and several tweets was deleted. My pc went on sleep mode, i found the process stopped, i restarted but i got this error. thanks.

I don't necessarily see any error here. Also only 12 + 2 results so I would guess most of your tweets have been deleted, if not all ?

**Comment by demerge** [comment]
Yeah, most of my tweets have been deleted thanks. Most of the tweets
remaining are repost. You might want to check that out.
